# MyHunterPlugin 配置文件

#-------------------------------------------------------------------------------
# Spawn Points - 游戏出生点及传送点设置
# 格式: "世界名称,x坐标,y坐标,z坐标,水平视角(yaw),垂直视角(pitch)"
# yaw (水平视角) 和 pitch (垂直视角) 是可选的, 如果不填写, 默认都是 0.
# 请确保世界名称正确, 并且坐标点在您的服务器地图上是合理且可到达的.
#-------------------------------------------------------------------------------
spawn_points:
  hunters: "world,0,65,10,0,0"    # 猎人出生点: 游戏开始时猎人传送到的位置.
  runners: "world,0,65,-10,180,0" # 逃亡者出生点: 游戏开始时逃亡者传送到的位置.
  end_game_teleport_location: "world,0,70,0,0,0" # 游戏结束后统一传送点: 游戏正常结束后, 参与者会被传送到这里.
  spectator: "world,0,100,0,0,0" # 旁观者出生点/逃亡者被抓捕后传送点: 逃亡者被抓捕或中途加入的玩家会到这里.

#-------------------------------------------------------------------------------
# Time Settings - 时间设置 (所有时间单位均为: 秒)
#-------------------------------------------------------------------------------
time_settings:
  preparation: 30       # 准备阶段时长: 游戏开始前的准备倒计时.
  game_duration: 600    # 游戏主要阶段时长: 例如 600 秒代表 10 分钟的游戏时间.

#-------------------------------------------------------------------------------
# NPC Interaction Task - NPC交互任务设置
# 逃亡者通过与特定NPC交互来完成的任务.
#-------------------------------------------------------------------------------
npc_interaction_task:
  npc_display_name: "&b任务使者" # 任务NPC在游戏内头顶显示的名称. 支持颜色代码.
  password_enabled: true         # 是否启用密码验证环节 (true: 启用, false: 禁用).
  password: "芝麻开门"             # NPC交互时需要输入的密码. 仅在 password_enabled 为 true 时生效.
  password_prompt_message: "&e请输入NPC的交互密码: " # NPC提示玩家输入密码时的消息.
  password_correct_message: "&a密码正确！正在处理你的任务..." # 玩家输入密码正确时的提示.
  password_incorrect_message: "&c密码错误！交互失败。" # 玩家输入密码错误时的提示.
  max_completions: 10           # 此任务最大可完成次数: 所有逃亡者共同争抢这些名额.
  identity_card:                # 逃亡者初始获得的身份卡物品设置.
    material: "PAPER"           # 身份卡物品的材质: 请使用 Spigot Material 枚举的准确名称 (通常为大写字母和下划线).
    display_name: "&b[身份证明]" # 身份卡物品在背包中显示的名称. 支持颜色代码.
    lore:                       # 身份卡物品的Lore描述 (鼠标悬停时显示的额外信息), 每行一个字符串.
      - "&7这是你作为逃亡者的证明。"
      - "&e右键任务NPC并输入正确密码提交。"
  task_completion_message: "&a任务完成！你消耗了一张身份证明。" # 成功完成NPC任务 (提交身份卡后) 时的提示.
  task_slots_full_message: "&eNPC任务名额已满，你无法再提交了！" # 当任务完成名额已满时, 玩家尝试交互得到的提示.
  glowing_duration_seconds: 60  # 发光效果持续时间: 未完成NPC任务的逃亡者, 在游戏结束或名额满时, 会获得发光效果, 单位秒.

#-------------------------------------------------------------------------------
# Flag Task - 旗帜收集与放置任务设置
# 逃亡者通过破坏特定旗帜并将其放置到指定地点的团队任务.
#-------------------------------------------------------------------------------
flag_task:
  enabled: true                 # 是否启用旗帜任务 (true: 启用, false: 禁用).
  required_flags_to_place: 3    # 逃亡者团队需要成功放置的旗帜总数才能完成此任务.
  target_placement_locations:   # 旗帜目标放置点坐标列表. 逃亡者需要将旗帜放置到这些精确的方块位置.
    - "world,10,64,10,0,0"
    - "world,-10,64,-10,0,0"
    - "world,10,64,-10,0,0"
  banner_material_to_pickup: "WHITE_BANNER" # 逃亡者需要破坏并拾取的旗帜方块的材质类型.
  flag_pickup_message: "&e你拾取了一面任务旗帜！快去指定地点放置吧！" # 逃亡者成功拾取旗帜时的提示信息.
  flag_placed_message: "&a旗帜放置成功！({COUNT}/{TOTAL})" # 成功放置旗帜到目标点时的提示 ({COUNT}会被替换为当前已放置数, {TOTAL}为总需放置数).
  flag_already_placed_message: "&c这个目标点已经有旗帜了！换个地方试试。" # 当目标点已被其他旗帜占据时的提示.
  flag_not_target_location_message: "&c这里不是旗帜的目标放置点！请对准目标点右键。" # 当玩家尝试在非目标点放置任务旗帜时的提示.
  task_success_broadcast: "&6[团队任务] &a逃亡者们成功收集并放置了所有旗帜！" # 旗帜任务全部完成时的全服广播消息.
  task_fail_broadcast: "&6[团队任务] &c遗憾！逃亡者们未能及时完成旗帜任务！" # 旗帜任务因时间耗尽等原因失败时的全服广播.
  banner_pickup_sound: "ENTITY_ITEM_PICKUP,1.0,1.0"   # 拾取旗帜音效 (SoundName,Volume,Pitch). 参考Spigot Sound枚举.
  banner_place_sound: "BLOCK_NOTE_BLOCK_PLING,1.0,1.2" # 成功放置旗帜音效.
  banner_place_fail_sound: "BLOCK_ANVIL_LAND,0.5,1.0"   # 放置旗帜失败音效 (如目标点错误或已有旗帜).

#-------------------------------------------------------------------------------
# Points System - 玩家积分系统 (用于头顶名称和Tab列表显示)
#-------------------------------------------------------------------------------
points_system:
  enabled: true # 是否启用自定义的头顶/Tab列表积分显示 (true: 启用, false: 禁用).
  points_per_npc_task_completion: 10 # 逃亡者每次成功完成NPC交互任务获得的积分数.
  points_per_flag_placed: 25         # 逃亡者每次成功放置一面旗帜获得的积分数.
  points_per_runner_caught: 50       # 猎人每次成功抓捕一名逃亡者获得的积分数.
  display_format: "&e[{points}] &r{player}" # 玩家名字在头顶和Tab列表中的显示格式. {player} 会被替换为玩家名, {points} 会被替换为玩家积分.

#-------------------------------------------------------------------------------
# Scoreboard Settings - 侧边栏公告榜设置
#-------------------------------------------------------------------------------
scoreboard:
  title: "&6&l猎人游戏"            # 侧边栏公告榜顶部的标题. 支持颜色代码.
  default_on_join: true         # 玩家加入服务器时是否默认开启显示此公告榜 (true: 开启, false: 关闭).
  footer:                       # 侧边栏公告榜底部显示的自定义信息 (可多行).
    - "&7--------------------"
    - "&eyourserver.com"

#-------------------------------------------------------------------------------
# Game Flow Settings - 游戏流程控制
#-------------------------------------------------------------------------------
game_flow:
  min_runners_to_start: 1       # 开始游戏所需的最少逃亡者数量 (不包括已设定的猎人).
  teleport_on_game_end: true    # 游戏结束时是否将所有参与者传送至上面 spawn_points.end_game_teleport_location 定义的地点 (true: 传送, false: 不传送).

#-------------------------------------------------------------------------------
# Hunter Specific Settings - 猎人特定设置
#-------------------------------------------------------------------------------
hunter_settings:
  weapon:                       # 猎人在游戏开始时 (RUNNING阶段开始时) 获得的特殊武器.
    material: "DIAMOND_SWORD"   # 武器的材质类型.
    name: "&c&l狩猎之刃"        # 武器的显示名称. 支持颜色代码.
    lore:                       # 武器的Lore描述.
      - "&4饮血，渴望猎物之魂。"
      - "&7用此利刃终结逃亡！"
  jail_location: "world,0,50,0,0,0" # 备用传送点: 主要用于 spawn_points.spectator 未配置时, 逃亡者被抓捕后的传送地点.